# Cloudflare Pages configuration

# Use Node.js 18 for builds
[build]
  command = "pnpm build"
  publish = "dist"
  # npm or pnpm for package manager
  # default to npm if not specified
  package_manager = "pnpm"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Handle SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Optimize asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 